### ISSUE TITLE
add search feature and download metafile along with stickers

### ISSUE THREAD

**Issue by thewayur** [targor/Line-Sticker-Downloader#3]
if i m not mistaken, some stickers have meta-info in their zip file, dont trim them please.

also it would be great if there will be some search or atleast filter option.

**Comment by targor** [comment]
Could you please describe the issue in more detail?
What meta information do you want to keep exactly, and why?

> also it would be great if there will be some search or atleast filter option.

Makes sense, but search is complicated, as the collections will be read in on demand to keep the cache small. It is possible but will take some time. I will add it to the planned feature list.

**Comment by thewayur** [comment]
about meta info, as i said, may be i m in doubt, i will describe it after re-research :D
(being developer meta info is necessary for handling and using it various apps e.g. categorization)

yes, i totatlly understand the complexity of search, and most of us should not have problem in inserting ID in the give box,


but can u atleast make it MULTIPLE IDS textarea? like one ID per line for bulk download?

if it is a matter of cache, u can provide a cache control option to user. thanks

ONE MORE THING
please add "about" in  box in ur software for tracking issues, so that we can easily note down the version in future




in future i may suggest more goodies for ur cute software (if u willing)
thanks for everything

**Comment by targor** [comment]
i added some of the requested features in the newest version. Search is still to be done, but as it is complicated, this will postponed to when there is time for it :)
